### PR TITLE
Compatibility with digital undumped games

### PR DESCRIPTION
**Pull request by mopi1402**
This one should works :
I check the eboot.bin to know if it's encrypted (undumped version) or not (dumped version).

Tested on Ridge Racer, Machinarium and Kung Fu Rabbit (dumped version).

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
Hello, I have plan about this, also use very similar method. so i'm not merge yet.
i'll test my code, then consider merge or not (or select some partial commit.) :)

**Comment by mopi1402** [comment]
As you like :)

I'm currently playing Final Fantasy X and it's more easy for me to use your homebrew than doing the job manually, that's why I don't waiting for your new release.

However I'm happy to see that you're working on a new version which will be compatible with undumped games, because I have a lot of legit games that I've started, and I believe that it's not possible to switch a save between legit and dumped games !

If you have time, you shoul'd prefer your own code, because C is not my favorite language. 
Malloc, pointers and all memory stuffs will kill me :)

Have a nice day ! And thank you for your work !

**Comment by d3m3vilurr** [comment]
Your codes partially applied into 05a1d2 2e45c71d 9b4a3959

Thanks for contribution!

**Comment by mopi1402** [comment]
It's better with cleaner code, hahaha ! :-)

**Pull request closed without merging**
